---
title: "StreamCatTools Demo"
author: "Marc Weber"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    highlighted: default 
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

## Install StreamCatTools
Also make sure you have nhdplusTools installed - I am leveraging some functions from that package to complement grabbing Streamcat data.  I'm also using mapview package.
```{r load libraries, eval=FALSE}
# requires devtools to install
install.packages('devtools')
library(devtools)

# install from repository
install_github('USEPA/StreamCatTools')
library(StreamCatTools)
library(nhdplusTools)
library(mapview)
```

## Access data for 
Look for joined fields in shapefile to figure out which states or hydroregions to load

```{r Regions_metrics}
library(readr)
library(dplyr)
# Variables
Region_type <- 'State' # or Hydroregions
metrics <-  c('CoalMines','ImperviousSurfaces2011')
temp_dir <- 'H:/WorkingData/Junk'

dat <- read_csv('F:/Git Projects/LouReynolds/Sites_with_Flags_and_NHDPlusInfo.csv')

if (Region_type=='State'){ 
  States = levels(as.factor(dat$state))
  for (s in States){
    for (m in metrics){
      download.file(paste0('ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/StreamCat/States/',m,'_',s,'.zip'),paste0(m,'_',s,'.zip'))
      unzip(paste0(m,'_',s,'.zip'),exdir = '.')
    }
  }
}

if (Region_type=='Hydroregions'){ 
  Hydroregions = levels(as.factor(dat$UnitID))
  for (h in Hydroregions){
    for (m in metrics){
      download.file(paste0('ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/StreamCat/HydroRegions/',m,'_',h,'.zip'),paste0(m,'_',h,'.zip'))
      unzip(paste0(m,'_',h,'.zip'),exdir = '.')
    }
  }
}
```

## Join StreamCat
```{r Join, eval=FALSE}
for (m in metrics){
  files = list.files('.', pattern = m)
  files = files[!grepl('\\.zip$',files)]
  temp <- lapply(files, read_csv)
  dat <- left_join(as.data.frame(dat), as.data.frame(temp))
}
write_csv(dat, 'Example_Output.csv')
```

